Gradient Decsent Recap:
![gradient-decsent](assests/gradient-decsent.png )

In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


Logistic Resgression with m Examples:
![logistic-resgression](assests/logistic-resgression-example.png )

In [9]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()


print(c)
print("Non-Vectorized: " + str(1000*(toc-tic)) + "ms")

249952.953269
Vectorized: 1.30200386047ms
249952.953269
Non-Vectorized: 506.256818771ms


#Broadcasting Example

In [11]:
A = np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [12]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [13]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [19]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c)
c.shape

[[ 21.47665818 -18.06637894  33.10775059 ...,   7.49312458   0.65613262
   11.34638971]
 [-11.73328477  10.25613555   5.57825644 ..., -29.3729745    7.78914002
  -21.30769481]
 [  6.41795205  17.04158634   1.161801   ...,   0.11718342 -13.44534387
   12.10254162]
 ..., 
 [ -4.30339898 -10.5510803   11.56919562 ...,   9.15103298   4.12463302
   10.438842  ]
 [ -4.72369685 -16.54411679  -5.79484221 ...,   1.59044501 -14.92868036
   -1.11652566]
 [-19.93839714  12.03349097  19.96022182 ...,  19.8772111   -3.54489535
  -12.91000718]]


(12288, 45)